---@omw-context menu|player

local textRules = require 'scripts.s3.ui.themes.textRules'
local ui = require 'openmw.ui'
local util = require 'openmw.util'

local function rgb(red, green, blue) return util.color.rgb(red / 255, green / 255, blue / 255) end

---@type H3UI.ThemeSpec
return {
  name = 'Morrowind',
  tokens = {
    color = {
      text = rgb(202, 165, 96),
      textHover = rgb(223, 201, 159),
      textPressed = rgb(243, 237, 221),
      active = rgb(96, 112, 202),
      activeHover = rgb(159, 169, 223),
      activePressed = rgb(223, 226, 244),
      disabled = rgb(179, 168, 135),
      disabledHover = rgb(223, 201, 159),
      disabledPressed = rgb(243, 237, 221),
      link = rgb(112, 126, 207),
      linkHover = rgb(143, 155, 218),
      linkPressed = rgb(175, 184, 228),
      journalLink = rgb(37, 49, 112),
      journalLinkHover = rgb(58, 77, 175),
      journalLinkPressed = rgb(112, 126, 207),
      journalTopic = rgb(0, 0, 0),
      journalTopicHover = rgb(58, 77, 175),
      journalTopicPressed = rgb(112, 126, 207),
      answer = rgb(150, 50, 30),
      answerHover = rgb(223, 201, 159),
      answerPressed = rgb(243, 237, 221),
      header = rgb(223, 201, 159),
      notify = rgb(223, 201, 159),
      bigText = rgb(202, 165, 96),
      bigTextHover = rgb(223, 201, 159),
      bigTextPressed = rgb(243, 237, 221),
      bigLink = rgb(112, 126, 207),
      bigLinkHover = rgb(143, 155, 218),
      bigLinkPressed = rgb(175, 184, 228),
      bigAnswer = rgb(150, 50, 30),
      bigAnswerHover = rgb(223, 201, 159),
      bigAnswerPressed = rgb(243, 237, 22),
      bigHeader = rgb(223, 201, 159),
      bigNotify = rgb(223, 201, 159),
      background = rgb(0, 0, 0),
      focus = rgb(80, 80, 80),
      health = rgb(200, 60, 30),
      magic = rgb(53, 69, 159),
      fatigue = rgb(0, 150, 60),
      misc = rgb(0, 205, 205),
      weaponFill = rgb(200, 60, 30),
      magicFill = rgb(200, 60, 30),
      positive = rgb(223, 201, 159),
      negative = rgb(200, 60, 30),
      count = rgb(223, 201, 159),
      accent = rgb(223, 201, 159),
      chromeBorder = rgb(202, 165, 96),
    },
    textSize = {
      normal = 16,
      header = 18,
    },
    transparency = {
      menu = 0.84,
    },
    spacing = {
      xs = 2,
      sm = 4,
      md = 2,
      lg = 4,
      xl = 6,
      padding = 2,
    },
    border = {
      normal = 2,
      thick = 4,
    },
    texture = {
      white = ui.texture { path = 'white' },
    },
  },
  chrome = {
    preferredSource = 'theme',
    frame = {
      thin = {
        thickness = 2,
        topLeft = 'textures/menu_thin_border_top_left_corner.dds',
        top = 'textures/menu_thin_border_top.dds',
        topRight = 'textures/menu_thin_border_top_right_corner.dds',
        left = 'textures/menu_thin_border_left.dds',
        right = 'textures/menu_thin_border_right.dds',
        bottomLeft = 'textures/menu_thin_border_bottom_left_corner.dds',
        bottom = 'textures/menu_thin_border_bottom.dds',
        bottomRight = 'textures/menu_thin_border_bottom_right_corner.dds',
      },
      thick = {
        thickness = 4,
        topLeft = 'textures/menu_thick_border_top_left_corner.dds',
        top = 'textures/menu_thick_border_top.dds',
        topRight = 'textures/menu_thick_border_top_right_corner.dds',
        left = 'textures/menu_thick_border_left.dds',
        right = 'textures/menu_thick_border_right.dds',
        bottomLeft = 'textures/menu_thick_border_bottom_left_corner.dds',
        bottom = 'textures/menu_thick_border_bottom.dds',
        bottomRight = 'textures/menu_thick_border_bottom_right_corner.dds',
      },
      button = {
        thickness = 4,
        tintable = true,
        topLeft = 'textures/menu_button_frame_top_left_corner.dds',
        top = 'textures/menu_button_frame_top.dds',
        topRight = 'textures/menu_button_frame_top_right_corner.dds',
        left = 'textures/menu_button_frame_left.dds',
        right = 'textures/menu_button_frame_right.dds',
        bottomLeft = 'textures/menu_button_frame_bottom_left_corner.dds',
        bottom = 'textures/menu_button_frame_bottom.dds',
        bottomRight = 'textures/menu_button_frame_bottom_right_corner.dds',
      },
    },
    caption = {
      thickness = 2,
      topLeft = 'textures/menu_head_block_top_left_corner.dds',
      top = 'textures/menu_head_block_top.dds',
      topRight = 'textures/menu_head_block_top_right_corner.dds',
      left = 'textures/menu_head_block_left.dds',
      center = 'textures/menu_head_block_middle.dds',
      right = 'textures/menu_head_block_right.dds',
      bottomLeft = 'textures/menu_head_block_bottom_left_corner.dds',
      bottom = 'textures/menu_head_block_bottom.dds',
      bottomRight = 'textures/menu_head_block_bottom_right_corner.dds',
    },
    pin = {
      up = {
        thickness = 2,
        topLeft = 'textures/menu_rightbuttonup_top_left.dds',
        top = 'textures/menu_rightbuttonup_top.dds',
        topRight = 'textures/menu_rightbuttonup_top_right.dds',
        left = 'textures/menu_rightbuttonup_left.dds',
        center = 'textures/menu_rightbuttonup_center.dds',
        right = 'textures/menu_rightbuttonup_right.dds',
        bottomLeft = 'textures/menu_rightbuttonup_bottom_left.dds',
        bottom = 'textures/menu_rightbuttonup_bottom.dds',
        bottomRight = 'textures/menu_rightbuttonup_bottom_right.dds',
      },
      down = {
        thickness = 2,
        topLeft = 'textures/menu_rightbuttondown_top_left.dds',
        top = 'textures/menu_rightbuttondown_top.dds',
        topRight = 'textures/menu_rightbuttondown_top_right.dds',
        left = 'textures/menu_rightbuttondown_left.dds',
        center = 'textures/menu_rightbuttondown_center.dds',
        right = 'textures/menu_rightbuttondown_right.dds',
        bottomLeft = 'textures/menu_rightbuttondown_bottom_left.dds',
        bottom = 'textures/menu_rightbuttondown_bottom.dds',
        bottomRight = 'textures/menu_rightbuttondown_bottom_right.dds',
      },
    },
    scroll = {
      up = 'textures/omw_menu_scroll_up.dds',
      down = 'textures/omw_menu_scroll_down.dds',
      left = 'textures/omw_menu_scroll_left.dds',
      right = 'textures/omw_menu_scroll_right.dds',
    },
  },
  rules = textRules(),
}
